image: tiangolo/docker-with-compose

stages:
  - build
  - deploy

build-cod1-swarm:
  stage: build
  tags:
    - cod1
  script:
    # Cache busters
    - rm config.js
    - sed -i -E "s/file=\"site\.json\"/file=\"site\.json\?v${CI_COMMIT_SHORT_SHA}\"/" index.html
    - docker-compose build
  only:
    - master
    - development

deploy-dev-cod1-swarm:
  stage: deploy
  variables:
    HOST: "odl-dev.courses.science.psu.edu"
    CONFIG_VARS: IMAGINARY_URL,IMAGINARY_HOST_URL
    IMAGINARY_URL: https://imaginary.courses.science.psu.edu
    IMAGINARY_HOST_URL: https://odl-dev.courses.science.psu.edu
  tags:
    - cod1
  script:
    - pwd
    - ls -la
    - docker stack deploy -c docker-compose.yml --resolve-image always odl-development
  only:
    - development

deploy-cod1-swarm:
  stage: deploy
  variables:
    HOST: "odl.science.psu.edu"
    CONFIG_VARS: IMAGINARY_URL,IMAGINARY_HOST_URL
    IMAGINARY_URL: https://imaginary.courses.science.psu.edu
    IMAGINARY_HOST_URL: https://odl.science.psu.edu
  tags:
    - cod1
  script:
    - pwd
    - ls -la
    - docker stack deploy -c docker-compose.yml --resolve-image always odl
  only:
    - master
