version: '3.3'
services:
  reverse-proxy:
    image: traefik:1.7 # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      # - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  
  # prod:
  #   build: .
  #   environment: 
  #     CONFIG_VARS: IMAGINARY_URL,IMAGINARY_HOST_URL
  #     IMAGINARY_URL: http://imaginary.traefik.me:9000
  #     IMAGINARY_HOST_URL: http://haxcms/sites/haxcms-odl
  #   labels:
  #     - "traefik.enable=true" # Enable reverse-proxy for this service
  #     - "traefik.frontend.rule=Host:odl.traefik.me"

  haxcms:
    image: elmsln/haxcms:1f7a2b4ae2
    volumes:
      - ./:/var/www/html/_sites/haxcms-odl:delegated
      - ./_config:/var/www/html/_config:delegated
      # - ../../build:/var/www/html/build
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:haxcms-odl.traefik.me"

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/haxcms:ro
      - ./services/api:/home/node/app
      - /home/node/app/node_modules
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.port=3000" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:haxcms-odl.traefik.me; PathPrefix:/service/api; ReplacePathRegex: ^/service/api(.*) $$1"

  custom:
    build:
      context: ./custom
    volumes:
      - ./custom:/home/node/app
      - /home/node/app/node_modules
  
  imaginary:
    image: h2non/imaginary:latest
    # optionally mount a volume as local image source
    volumes:
      - /mnt/data
    environment:
       PORT: 9000
    command: -enable-url-source -mount /mnt/data
    ports:
      - "9000:9000"