version: '3.7'
services:

  haxcms:
    build:
      context: .
    image: haxcms-haxcms-odl:${CI_COMMIT_SHORT_SHA:-latest}
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:odl.${HOST:-docker.localhost}"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.rule=Host:odl.${HOST:-docker.localhost}"
        - "traefik.tags=traefik-public"
        - "traefik.frontend.auth.basic.users=${BASIC_AUTH_CONFIG}"
      replicas: 1
      update_config:
        order: start-first

  hax-forms-service:
    image: heymp/hax-forms-service:89a105e93f6f40a97f43609b3af2b7d6f5cf768e
    networks:
      - traefik-public
    environment:
      - EMAIL=odlformsservice@gmail.com
      - CORS_ORIGIN=http://odl.courses.science.psu.edu
      - EMAIL_TEMPLATE_HEADER=ODL Form Submission
      - EMAIL_FROM_ADDRESS='ODL Website'<odlformsservice@gmail.com>
      - EMAIL_TO_ADDRESS=mgp140@gmail.com
      - EMAIL_SUBJECT=ODL Form Submission
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=4000"
        - "traefik.frontend.rule=Host:hax-forms-service.odl.${HOST:-docker.localhost}"
        - "traefik.docker.network=traefik-public"
        - "traefik.tags=traefik-public"
      replicas: 1
      update_config:
        order: start-first

networks:
  traefik-public:
    external: true