version: '3.7'
services:

  haxcms:
    build:
      context: .
    image: haxcms-haxcms-odl:${CI_COMMIT_SHORT_SHA:-latest}
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:odl.${HOST:-docker.localhost}"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.rule=Host:odl.${HOST:-docker.localhost},odl.science.psu.edu;"
        - "traefik.tags=traefik-public"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        # - "traefik.frontend.auth.basic.users=${BASIC_AUTH_CONFIG}"
      replicas: 1
      update_config:
        order: start-first

  api:
    build:
      context: ./services/api
    image: api-haxcms-odl:${CI_COMMIT_SHORT_SHA:-latest}
    volumes:
      - ./site.json:/haxcms/site.json
      - ./pages:/haxcms/pages
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true" # Enable reverse-proxy for this service
        - "traefik.port=3000" # Enable reverse-proxy for this service
        - "traefik.frontend.rule=Host:haxcms-odl.haxcms.localhost; PathPrefix:/service/api; ReplacePathRegex: ^/service/api(.*) $$1"
        - "traefik.tags=traefik-public"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
      replicas: 1
      update_config:
        order: start-first

  hax-forms-service:
    image: heymp/hax-forms-service:next
    command: 'yarn run dev'
    networks:
      - traefik-public
    environment:
      - EMAIL=odlformsservice@gmail.com
      - EMAIL_PASSWORD=odl_hax_form_email_password
      - CORS_ORIGIN=https://odl.courses.science.psu.edu
      - EMAIL_TEMPLATE_HEADER=ODL Form Submission
      - EMAIL_FROM_ADDRESS='ODL Website'<odlformsservice@gmail.com>
      - EMAIL_TO_ADDRESS=odl@science.psu.edu
      - EMAIL_SUBJECT=ODL Form Submission
      - RECAPTCHA_SECRET=odl_recaptcha_secret
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=4000"
        - "traefik.frontend.rule=Host:hax-forms-service.odl.${HOST:-docker.localhost}"
        - "traefik.docker.network=traefik-public"
        - "traefik.tags=traefik-public"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
      replicas: 1
      update_config:
        order: start-first
    secrets:
      - odl_hax_form_email_password
      - odl_recaptcha_secret

secrets:
  odl_hax_form_email_password:
    external: true
  odl_recaptcha_secret:
    external: true

networks:
  traefik-public:
    external: true